# Generated by Django 4.1.3 on 2022-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('b_date', models.DateTimeField()),
                ('reg_no', models.IntegerField()),
                ('department', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
            ],
        ),
    ]
